const styles = {
    backgroundStyle: {
        display: 'flex',
        height: '100vh',
        backgroundColor: '#1e1e1e',
        color: 'white',
        overflow: 'hidden',
    },
    leftBlockStyle: {
        width: '50%',
        padding: '30px',
        borderRight: '1.5px solid white',
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'flex-start',
    },
    rightBlockStyle: {
        width: '50%',
        padding: '30px',
        position: 'relative',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
    },
    userContainerStyle: {
        display: 'flex',
        alignItems: 'center',
        marginBottom: '30px',
    },
    avatarStyle: {
        width: '60px',
        height: '60px',
        borderRadius: '50%',
        backgroundColor: 'gray',
        marginRight: '15px',
    },
    usernameStyle: {
        fontSize: '27px',
        color: 'white',
        textDecoration: 'none',
    },
    myRoomsStyle: {
        color: 'white',
        fontSize: '27px',
    },
    searchContainerStyle: {
        display: 'flex',
        alignItems: 'center',
        marginBottom: '30px',
    },
    searchInputStyle: {
        width: '40%',
        padding: '12px',
        borderRadius: '7.5px',
        border: '1.5px solid white',
        backgroundColor: '#333',
        color: 'white',
    },
    searchIconStyle: {
        marginLeft: '15px',
    },
    roomListStyle: {
        display: 'flex',
        flexDirection: 'column',
    },
    roomItemStyle: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        padding: '15px',
        borderBottom: '1.5px solid white',
    },
    roomAvatarStyle: {
        width: '60px',
        height: '60px',
        backgroundColor: 'gray',
        marginRight: '15px',
    },
    roomNameStyle: {
        flex: 1,
        marginLeft: '15px',
    },
    createRoomStyle: {
        display: 'flex',
        alignItems: 'center',
        padding: '15px',
        marginTop: '30px',
        borderTop: '1.5px solid white',
        cursor: 'pointer',
    },
    plusIconStyle: {
        color: 'red',
        marginRight: '15px',
    },
    joinRoomStyle: {
        marginBottom: '30px',
        fontSize: '27px',
    },
    smallInputStyle: {
        width: '60%',
        padding: '12px',
        marginBottom: '15px',
        borderRadius: '7.5px',
        border: '1.5px solid white',
        backgroundColor: '#333',
        color: 'white',
    },
    connectButtonStyle: {
        padding: '15px 30px',
        borderRadius: '7.5px',
        border: 'none',
        backgroundColor: '#337a3c',
        color: 'white',
        cursor: 'pointer',
    },
    settingsIconStyle: {
        position: 'absolute',
        top: '30px',
        right: '30px',
        cursor: 'pointer',
    },
    modalOverlayStyle: {
        position: 'fixed',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
    },
    modalStyle: {
        backgroundColor: '#1e1e1e',
        padding: '20px',
        borderRadius: '10px',
        width: '280px',
        textAlign: 'center',
        border: '2px solid #337a3c',
    },
    modalInputStyle: {
        width: '90%',
        padding: '8px',
        margin: '10px 0',
        borderRadius: '5px',
        border: '1px solid #ccc',
    },
    createButtonStyle: {
        padding: '10px 20px',
        margin: '10px 5px',
        borderRadius: '5px',
        border: 'none',
        backgroundColor: '#138513',
        color: 'white',
        cursor: 'pointer',
    },
    cancelButtonStyle: {
        padding: '10px 20px',
        margin: '10px 5px',
        borderRadius: '5px',
        border: 'none',
        backgroundColor: '#8c0b0b',
        color: 'white',
        cursor: 'pointer',
    },
};

export default styles;
